export const CREATE_RECIPE = "CREATE_RECIPE";
export const FETCH_RECIPE = "FETCH_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const FETCH_RECIPES = "FETCH_RECIPES";
